services:
  - type: web
    name: auto-filter-bot
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: MONGO_URI
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: ADMINS
        sync: false
